# Generated by Django 5.2.16 on 2026-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='moneda')),
                ('method', models.CharField(choices=[('card', 'Tarjeta'), ('nequi', 'Nequi')], default='card', max_length=10, verbose_name='método')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('succeeded', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de PaymentIntent')),
                ('stripe_client_secret', models.TextField(blank=True, verbose_name='client_secret')),
                ('nequi_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID transacción Nequi')),
                ('nequi_phone_number', models.CharField(blank=True, max_length=20, verbose_name='teléfono Nequi del cliente')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='nombre del cliente')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='email del cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono del cliente')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'), models.Index(fields=['nequi_transaction_id'], name='payments_pa_nequi_t_7d052a_idx')],
            },
        ),
    ]
